cdr_products:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'cdr') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'cdr') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'cdr') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
