version: 2

sources:
  - name: raw
    schema: raw
    freshness:
      warn_after: {count: 2, period: day}
      error_after: {count: 7, period: day}
    tables:
      - name: products_raw
        loaded_at_field: fetched_at
      - name: product_detail_raw
        loaded_at_field: fetched_at
  - name: bronze
    schema: bronze
    tables:
      - name: api_call_log
        loaded_at_field: fetched_at
      - name: pipeline_run
      - name: data_holder_brand
      - name: schema_drift_event
